# Generated by Django 5.2.13 on 2026-04-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_is_active_project_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('paused', 'Paused'), ('finished', 'Finished')], default='active', max_length=20, verbose_name='Status'),
        ),
    ]
