# Generated by Django 5.2.13 on 2026-04-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcontractors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcontractor',
            options={'ordering': ['name'], 'verbose_name': 'Subcontractor', 'verbose_name_plural': 'Subcontractors'},
        ),
        migrations.AlterField(
            model_name='subcontractor',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='subcontractor',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Name'),
        ),
        migrations.AlterField(
            model_name='subcontractor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='subcontractor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='subcontractor',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subcontractor',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='subcontractor',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='subcontractor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='subcontractor',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='VAT Number'),
        ),
        migrations.AddConstraint(
            model_name='subcontractor',
            constraint=models.UniqueConstraint(condition=models.Q(('vat_number', ''), _negated=True), fields=('vat_number',), name='unique_vat_number'),
        ),
    ]
