# Generated by Django 5.2.13 on 2026-04-13 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
        migrations.AddField(
            model_name='client',
            name='category',
            field=models.CharField(blank=True, choices=[('private', 'Privé'), ('professional', 'Professionnel')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='legal_form',
            field=models.CharField(blank=True, choices=[('mr', 'Monsieur'), ('mrs', 'Madame'), ('company', 'Entreprise')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Informations'),
        ),
        migrations.AddField(
            model_name='client',
            name='responsible',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='client',
            name='trade_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom commercial'),
        ),
        migrations.AddField(
            model_name='client',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxe TVA (%)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Raison sociale'),
        ),
        migrations.AlterField(
            model_name='client',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TVA'),
        ),
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(max_length=255)),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('complement', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='Belgium', max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('general', 'Général'), ('financial', 'Finance'), ('commercial', 'Commercial')], default='general', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clients.client')),
            ],
        ),
    ]
