# Generated by Django 5.2.13 on 2026-04-13 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_address_remove_client_company_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='clientaddress',
            options={'verbose_name': 'Adresse', 'verbose_name_plural': 'Adresses'},
        ),
        migrations.AlterModelOptions(
            name='clientcontact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterField(
            model_name='client',
            name='category',
            field=models.CharField(blank=True, choices=[('private', 'Privé'), ('professional', 'Professionnel')], max_length=20, null=True, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='client',
            name='legal_form',
            field=models.CharField(blank=True, choices=[('mr', 'Monsieur'), ('mrs', 'Madame'), ('company', 'Entreprise')], max_length=20, null=True, verbose_name='Forme juridique'),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='clients.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='complement',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Complément'),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='country',
            field=models.CharField(default='Belgium', max_length=100, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Adresse par défaut'),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='postal_code',
            field=models.CharField(max_length=20, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Région'),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='street',
            field=models.CharField(max_length=255, verbose_name='Rue'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clients.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='contact_type',
            field=models.CharField(choices=[('general', 'Général'), ('financial', 'Finance'), ('commercial', 'Commercial')], default='general', max_length=20, verbose_name='Type de contact'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Contact principal'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Site web'),
        ),
    ]
