# Generated by Django 5.2.13 on 2026-04-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_manager_user_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Utilizador', 'verbose_name_plural': 'Utilizadores'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_manager',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('manager', 'Gestor de Obra'), ('supervisor', 'Encarregado'), ('office', 'Escritório')], db_index=True, default='office', max_length=20, verbose_name='Perfil'),
        ),
    ]
