# Generated by Django 5.2.13 on 2026-04-15 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_alter_project_status'),
        ('subcontractors', '0002_alter_subcontractor_options_and_more'),
        ('workforce', '0002_insurancefund_alter_collaborator_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings', to='projects.project')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'project')},
            },
        ),
        migrations.CreateModel(
            name='PlanningWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('full_day', 'Full Day'), ('morning', 'Morning'), ('afternoon', 'Afternoon'), ('custom', 'Custom')], default='full_day', max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('is_present', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_workers', to='planning.planning')),
                ('subcontractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_plannings', to='subcontractors.subcontractor')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_assignments', to='workforce.collaborator')),
            ],
            options={
                'ordering': ['planning__date', 'worker'],
            },
        ),
        migrations.CreateModel(
            name='PlanningSubcontractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_subcontractors', to='planning.planning')),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_assignments', to='subcontractors.subcontractor')),
            ],
            options={
                'ordering': ['planning'],
                'unique_together': {('planning', 'subcontractor')},
            },
        ),
    ]
