# Generated by Django 5.2.13 on 2026-04-15 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Insurance Fund',
                'verbose_name_plural': 'Insurance Funds',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='CollaboratorHourlyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Hourly Rate')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_rates', to='workforce.collaborator')),
            ],
            options={
                'verbose_name': 'Hourly Rate',
                'verbose_name_plural': 'Hourly Rates',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='collaborator',
            name='insurance_fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collaborators', to='workforce.insurancefund', verbose_name='Insurance Fund'),
        ),
        migrations.CreateModel(
            name='InsuranceFundContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('role', models.CharField(blank=True, max_length=100, null=True, verbose_name='Role')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='workforce.insurancefund')),
            ],
            options={
                'verbose_name': 'Insurance Fund Contact',
                'verbose_name_plural': 'Insurance Fund Contacts',
            },
        ),
    ]
